users: ["U01", "U02", "U03", "U04", "U05", "U06", "U07", "U08"]
gestures:
  - "01"
  - "02"
  - "03"
  - "04"
  - "05"
  - "06"
  - "07"
  - "08"
  - "09"
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
  - "15"
  - "16"
  - "17"
  - "18"
  - "19"
  - "20"

wavelet_name: db1

dataset:
  path: gestures-dataset
  split_point: 2449
  split_point_6: 735

knn:
  neighbors:
    min: 2
    max: 100

decision_tree:
  depth:
    min: 2
    max: 50

random_forest:
  estimators:
    min: 2
    max: 1200
    step: 100
